### ISSUE TITLE
[Feat] 책 등록 시, 출판사 컬럼까지 저장

### ISSUE THREAD

**Issue by yeseul106** [team-peekabook/Peekabook-server#159]
📌 Api detail
---
- 책구분할 때 → 책이름, 작가로만 하는게 아니라 출판사까지 고려해야 원하는 표지가 나올 것 같음 (책 검색하고 DB에 저장할 때)
- 내 책장에 책 등록 api 리팩토링까지 같이 진행하겠습니당

✔️ To do
---
- [x] 출판사 컬럼 추가해야할듯
- [x] 내 책장에 책 등록 api 리팩토링

**Comment by 2zerozu** [comment]
👀
